// Code generated by mockery v1.0.0. DO NOT EDIT.

package vulnsrc

import mock "github.com/stretchr/testify/mock"

// MockOptimizer is an autogenerated mock type for the Optimizer type
type MockOptimizer struct {
	mock.Mock
}

type OptimizeReturns struct {
	Err error
}

type OptimizeExpectation struct {
	Returns OptimizeReturns
}

func (_m *MockOptimizer) ApplyOptimizeExpectation(e OptimizeExpectation) {
	var args []interface{}
	_m.On("Optimize", args...).Return(e.Returns.Err)
}

func (_m *MockOptimizer) ApplyOptimizeExpectations(expectations []OptimizeExpectation) {
	for _, e := range expectations {
		_m.ApplyOptimizeExpectation(e)
	}
}

// Optimize provides a mock function with given fields:
func (_m *MockOptimizer) Optimize() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
