// Code generated by mockery v1.0.0. DO NOT EDIT.

package vulnsrc

import db "github.com/aquasecurity/trivy-db/pkg/db"
import mock "github.com/stretchr/testify/mock"

// MockOperation is an autogenerated mock type for the Operation type
type MockOperation struct {
	mock.Mock
}

type SetMetadataArgs struct {
	_a0         db.Metadata
	_a0Anything bool
}

type SetMetadataReturns struct {
	_a0 error
}

type SetMetadataExpectation struct {
	Args    SetMetadataArgs
	Returns SetMetadataReturns
}

func (_m *MockOperation) ApplySetMetadataExpectation(e SetMetadataExpectation) {
	var args []interface{}
	if e.Args._a0Anything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args._a0)
	}
	_m.On("SetMetadata", args...).Return(e.Returns._a0)
}

func (_m *MockOperation) ApplySetMetadataExpectations(expectations []SetMetadataExpectation) {
	for _, e := range expectations {
		_m.ApplySetMetadataExpectation(e)
	}
}

// SetMetadata provides a mock function with given fields: _a0
func (_m *MockOperation) SetMetadata(_a0 db.Metadata) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(db.Metadata) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
