// Code generated by mockery v1.0.0. DO NOT EDIT.

package vulnsrc

import mock "github.com/stretchr/testify/mock"

// MockVulnSrc is an autogenerated mock type for the VulnSrc type
type MockVulnSrc struct {
	mock.Mock
}

type UpdateArgs struct {
	_a0         string
	_a0Anything bool
}

type UpdateReturns struct {
	_a0 error
}

type UpdateExpectation struct {
	Args    UpdateArgs
	Returns UpdateReturns
}

func (_m *MockVulnSrc) ApplyUpdateExpectation(e UpdateExpectation) {
	var args []interface{}
	if e.Args._a0Anything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args._a0)
	}
	_m.On("Update", args...).Return(e.Returns._a0)
}

func (_m *MockVulnSrc) ApplyUpdateExpectations(expectations []UpdateExpectation) {
	for _, e := range expectations {
		_m.ApplyUpdateExpectation(e)
	}
}

// Update provides a mock function with given fields: _a0
func (_m *MockVulnSrc) Update(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
