// Code generated by mockery v1.0.0. DO NOT EDIT.

package vulnsrc

import mock "github.com/stretchr/testify/mock"

// MockVulnSrc is an autogenerated mock type for the VulnSrc type
type MockVulnSrc struct {
	mock.Mock
}

type UpdateArgs struct {
	Dir         string
	DirAnything bool
}

type UpdateReturns struct {
	Err error
}

type UpdateExpectation struct {
	Args    UpdateArgs
	Returns UpdateReturns
}

func (_m *MockVulnSrc) ApplyUpdateExpectation(e UpdateExpectation) {
	var args []interface{}
	if e.Args.DirAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dir)
	}
	_m.On("Update", args...).Return(e.Returns.Err)
}

func (_m *MockVulnSrc) ApplyUpdateExpectations(expectations []UpdateExpectation) {
	for _, e := range expectations {
		_m.ApplyUpdateExpectation(e)
	}
}

// Update provides a mock function with given fields: dir
func (_m *MockVulnSrc) Update(dir string) error {
	ret := _m.Called(dir)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(dir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
