---
version: 2
updates:
  - package-ecosystem: gomod
    target-branch: chore/dependabot
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    target-branch: chore/dependabot
    directory: /
    schedule:
      interval: weekly
